### ISSUE TITLE
looks like does not work on surface pro 10

### ISSUE THREAD

**Issue by ocean1ee1** [linux-surface/linux-surface#1467]
I installed a latest LTS version for Ubuntu - 24.04
And then installed linux-surface step by step according to this document https://github.com/linux-surface/linux-surface/wiki/Installation-and-Setup#Debian--Ubuntu

after all steps finished, many things still not work, such as, keyboard, touchscreen, battery status, etc.
### Environment

- Hardware model: Surface Pro 10 for business
- Kernel version: Linux xxxxx 6.9.3-surface-2 # 2 SMP PREEMPT_DYNAMIC Mon Jun 10 23:37:21 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
- Distribution: Ubuntu 24.04 LTS

dmesg output is attached to this file
[newdmesg.txt](https://github.com/user-attachments/files/15840278/newdmesg.txt)

It's too long for this post

**Comment by qzed** [comment]
Each new device requires some amount of bring-up, so this is pretty much expected. If MS didn't change much, it should be fairly easy to at least enable support for the battery status and keyboard cover. Touchscreen might need some more time (CC @quo, @StollD ).

Could you run the `diagnostics.sh` script mentioned [here](https://github.com/linux-surface/linux-surface/wiki/Testers-and-Contributing#support-for-new-devices) and upload the archive it creates?

**Comment by ocean1ee1** [comment]
[diagnostics.tar.gz](https://github.com/user-attachments/files/15846053/diagnostics.tar.gz)

Here is the results and hope this helpful, thanks

**Comment by quo** [comment]
Installing the latest version of [ithc](https://github.com/quo/ithc-linux) should make the touchscreen work.

**Comment by ocean1ee1** [comment]
@quo,@qzed

Since I don't have much experience. Please forgive me if ask silly or bad questions.

From  [ithc](https://github.com/quo/ithc-linux) and [IPTSD](https://github.com/linux-surface/iptsd) pages, both of them mentioned they were included in Linux Surface kernel.

Since I installed the latest Linux Surface kernel several days ago. I wonder if the latest Linux Surface kernel(seems updated in last week) whether includes the latest [ithc](https://github.com/quo/ithc-linux) (seems updated in 3 weeks ago) or not?

Or is there any file in my system that indicates my ithc version is not latest?

**Comment by quo** [comment]
@ocean1ee1 The last two ithc commits should make the driver work with Meteor Lake devices such as the Surface Pro 10 and Surface Laptop 6. But so far these changes have only been confirmed to work on a ThinkBook, so they are not yet included in the Linux Surface kernel. Once someone actually confirms they work with the SP10 and/or SL6, the changes can be added to the Surface kernel.

**Comment by ocean1ee1** [comment]
@quo With a very short test, after installed the latest ithc, touchscreen works.

Is there any more detail test steps for these touchscreen features? When I have more time, I plan to install some apps which supported pen to test more.

Btw, IMO my installation process is not so easy for a newbie, maybe the guideline can have more tips

I installed a ubuntu 24.04.

Tried  [Installation without DKMS ] method first, and met a signing file problem - no such libcypto.so.1.1 file.

And then tried [Installation with DKMS ] second, and the output showed the same module and then would not replace.

and tried this command - sudo modprobe ithc
modprobe: ERROR: could not insert 'ithc': Key was rejected by service

and reboot, the touchscreen still not work.

According to several old issues by searching, I renamed the ithc,ko and used DKMS install method, and then works

**Comment by quo** [comment]
@ocean1ee1 Nice, thanks for testing!
The libcrypto error seems to be a known issue: https://github.com/linux-surface/kernel/issues/134

@StollD So the last couple ithc commits enable SL6 and SP10 support. Feel free to merge when you have some time.

**Comment by ocean1ee1** [comment]
> Each new device requires some amount of bring-up, so this is pretty much expected. If MS didn't change much, it should be fairly easy to at least enable support for the battery status and keyboard cover. Touchscreen might need some more time (CC @quo, @StollD ).
> 
> Could you run the `diagnostics.sh` script mentioned [here](https://github.com/linux-surface/linux-surface/wiki/Testers-and-Contributing#support-for-new-devices) and upload the archive it creates?

@qzed , sorry to bother you, I guess you are very busy these days. Is there any estimated date or rough plan to support keyboard and battery status in SP10? Or it there any guidelines or articles if I would like to try to fix these by myself(not sure the possibility and difficulties)

**Comment by qzed** [comment]
Essentially, what you need to do to enable SAM is something like [this](https://github.com/linux-surface/linux-surface/issues/1463#issuecomment-2159176025). You can probably just copy the [definitions from the SP9](https://github.com/linux-surface/kernel/blob/46328c684daecf5376e527df67dcdd524d2b8fdb/drivers/platform/surface/surface_aggregator_registry.c#L357-L374) and then add the respective [reference](https://github.com/linux-surface/kernel/blob/46328c684daecf5376e527df67dcdd524d2b8fdb/drivers/platform/surface/surface_aggregator_registry.c#L392-L393) for it. The device ID should be `MSHW0510`.

So hopefully something like the patch below should do the trick. If you can, please give that a try (that should enable keyboard, touchpad, battery info, HID-based sensors, the ACPI/platform profile and fan speed info and control via the platform profile). If you do, please also upload a dmesg log. 

```diff
From a8999300cee837af53f100adfd76a1ba2d37859a Mon Sep 17 00:00:00 2001
From: Maximilian Luz <luzmaximilian@gmail.com>
Date: Fri, 28 Jun 2024 22:31:37 +0200
Subject: [PATCH] platform/surface: aggregator_registry: Add Support for
 Surface Pro 10

---
 .../surface/surface_aggregator_registry.c     | 22 +++++++++++++++++++
 1 file changed, 22 insertions(+)

diff --git a/drivers/platform/surface/surface_aggregator_registry.c b/drivers/platform/surface/surface_aggregator_registry.c
index 07a4c4e1120d3..a6e7dac2fd4b1 100644
--- a/drivers/platform/surface/surface_aggregator_registry.c
+++ b/drivers/platform/surface/surface_aggregator_registry.c
@@ -373,6 +373,25 @@ static const struct software_node *ssam_node_group_sp9[] = {
 	NULL,
 };
 
+/* Devices for Surface Pro 10 */
+static const struct software_node *ssam_node_group_sp10[] = {
+	&ssam_node_root,
+	&ssam_node_hub_kip,
+	&ssam_node_bat_ac,
+	&ssam_node_bat_main,
+	&ssam_node_tmp_perf_profile_with_fan,
+	&ssam_node_tmp_sensors,
+	&ssam_node_fan_speed,
+	&ssam_node_pos_tablet_switch,
+	&ssam_node_hid_kip_keyboard,
+	&ssam_node_hid_kip_penstash,
+	&ssam_node_hid_kip_touchpad,
+	&ssam_node_hid_kip_fwupd,
+	&ssam_node_hid_sam_sensors,
+	&ssam_node_hid_sam_ucm_ucsi,
+	NULL,
+};
+
 
 /* -- SSAM platform/meta-hub driver. ---------------------------------------- */
 
@@ -395,6 +414,9 @@ static const struct acpi_device_id ssam_platform_hub_match[] = {
 	/* Surface Pro 9 */
 	{ "MSHW0343", (unsigned long)ssam_node_group_sp9 },
 
+	/* Surface Pro 10 */
+	{ "MSHW0510", (unsigned long)ssam_node_group_sp10 },
+
 	/* Surface Book 2 */
 	{ "MSHW0107", (unsigned long)ssam_node_group_gen5 },
 
-- 
2.45.1
```

**Comment by ocean1ee1** [comment]
@qzed，

I complied a kernel with your modification in surface_aggregator_registry.c and installed it(currently have to disable secure boot to boot with this custom kernel).

With a short look, keyboard and battery info should work as normal.

Here is the new log, hope these info helpful. No sure is there still some errors
[dmesg_after.log](https://github.com/user-attachments/files/16071063/dmesg_after.log)

**Comment by qzed** [comment]
The log looks fine. If you run `sensors` it should also show some SAM based temperature readings as well as fan speed.

**Comment by ocean1ee1** [comment]
yes, you are right, sensors shows temperature and fan speed.

**Comment by qzed** [comment]
Thanks! Looks fine so far then. I'll add it to our patches when I have some time.

**Comment by qzed** [comment]
The patch will be included in the next release (v6.9.9).

**Comment by ocean1ee1** [comment]
Great, thanks, I plan to close this issue after upgrade to latest version from apt and do some quick check.

**Comment by ocean1ee1** [comment]
@qzed Sorry to bother you.

Looks like I met some problems after tried to  install the latest kernel (6.10.3-1)  from apt source (ubuntn 24.04)

First I started the system with my complied kernel and upgraded the linux surface image from apt upgrade, it return some errors: ithc no found.

From grub menu, I cannot start the system with 6.10.3-1 kernel

Then, I started the system with my complied kernel and purged the 6.10.3-1 kernel(image and header)

And then, I started the system with old official surface 6.9.3 kernel and installed the 6.10.3-1 kernel(image and header) again. This time no error showed.

BUT, I tried to start the system with 6.10.3-1 kernel, it would stuck in 
Loading linux 6.10.3-surface-1 ...
Loading initial ramdisk ...

I'm not sure my experience may relate to my complied kernel or a common issue?

Normally when upgrade the surface kernel, I should start system with old official kernel or I can start with my own complied kernel?  

Is there any steps I can fix my problem from my side?

**Comment by qzed** [comment]
Looks like there might be something wrong with our latest Debian/Ubuntu release: https://github.com/linux-surface/linux-surface/issues/1516.

**Comment by qzed** [comment]
> Normally when upgrade the surface kernel, I should start system with old official kernel or I can start with my own complied kernel?

You should be able to start your own kernel. As far as I know, there's no need to start with a specific one after updating.

**Comment by mrzlsptzr** [comment]
I'm planning to buy a Surface and I'm not sure whether it should be SP9 or SP10 because I want to use Arch Linux as my OS.
@ocean1ee1 Can you tell me what is still not working?

**Comment by ocean1ee1** [comment]
@mrzlsptzr ,

Please note, since currently I still installed and used my customized kernel based on 6.9.X surface kernel, not sure what's changed between the latest kernel 6.10 and mine, the latest kernel may supported more feature. Also another point, I only used Ubuntu in my surface, not sure whether there are the differences between Ubuntu and Arch distributions.

Right now, camera cannot work. And in most time I will use Ubuntu from this device, it seems touch screen, keyboard, bluetooth, wifi, usb 4, cpu fan work fine. 

Only several times meet these weird touch screen not working issue after suspend(do not remember the steps), unexpected reboot. And my device cannot shutdown system completely (I had to reboot to grup menu and then shutdown, I saw other people met the issue in other places) 
These issues may not be caused by this kernel

One more thing, please make sure the SP10 you are talking about is real SP10 edition. In this year MS releases a new surface pro with Snapdragon CPU, named NEW surface pro / surface pro Copilot+ PC, / surface pro X / surface pro 11 . The names may make confusion. I guess this kernel DOES NOT support this device right now.

The CPU processor of my surface pro 10 device is from INTEL Ultra.

**Comment by ocean1ee1** [comment]
@qzed @quo 

Very strange, looks like I still cannot upgrade to latest kernel (6.10.10-surface-1) via apt upgrade.

I used below command to install:

sudo apt install linux-image-surface linux-headers-surface libwacom-surface iptsd


------------------
Got below output information:

Setting up linux-image-6.10.10-surface-1 (6.10.10-surface-1) ...
 * dkms: running auto installation service for kernel 6.10.10-surface-1
Sign command: /usr/bin/kmodsign
Signing key: /var/lib/shim-signed/mok/MOK.priv
Public certificate (MOK): /var/lib/shim-signed/mok/MOK.der

Building module:
Cleaning build area...
make -j14 KERNELRELEASE=6.10.10-surface-1 KDIR=/lib/modules/6.10.10-surface-1/build...(bad exit status: 2)
ERROR (dkms apport): binary package for ithc: 0.1 not found
Error! Bad return status for module build on kernel: 6.10.10-surface-1 (x86_64)
Consult /var/lib/dkms/ithc/0.1/build/make.log for more information.
dkms autoinstall on 6.10.10-surface-1/x86_64 succeeded for fwts-efi-runtime-dkms
dkms autoinstall on 6.10.10-surface-1/x86_64 failed for ithc(10)
Error! One or more modules failed to install during autoinstall.

-----------------
The content of /var/lib/dkms/ithc/0.1/build/make.log:

DKMS make.log for ithc-0.1 for kernel 6.10.10-surface-1 (x86_64)
Thu Sep 26 03:42:32 PM CST 2024
mkdir -p build
find build/ -type l -exec rm {} +
ln -sr src/* build/
make -C /lib/modules/6.10.10-surface-1/build M=/var/lib/dkms/ithc/0.1/build/build CONFIG_HID_ITHC=m
make[1]: Entering directory '/usr/src/linux-headers-6.10.10-surface-1'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
  You are using:           gcc (Ubuntu 13.2.0-23ubuntu4) 13.2.0
  CC [M]  /var/lib/dkms/ithc/0.1/build/build/ithc-main.o
  CC [M]  /var/lib/dkms/ithc/0.1/build/build/ithc-regs.o
  CC [M]  /var/lib/dkms/ithc/0.1/build/build/ithc-dma.o
  CC [M]  /var/lib/dkms/ithc/0.1/build/build/ithc-hid.o
  CC [M]  /var/lib/dkms/ithc/0.1/build/build/ithc-legacy.o
  CC [M]  /var/lib/dkms/ithc/0.1/build/build/ithc-quickspi.o
  CC [M]  /var/lib/dkms/ithc/0.1/build/build/ithc-debug.o
/var/lib/dkms/ithc/0.1/build/build/ithc-dma.c: In function ‘ithc_dma_data_devres_release’:
/var/lib/dkms/ithc/0.1/build/build/ithc-dma.c:47:17: error: implicit declaration of function ‘vunmap’; did you mean ‘kunmap’? [-Werror=implicit-function-declaration]
   47 |                 vunmap(sgt->addr);
      |                 ^~~~~~
      |                 kunmap
/var/lib/dkms/ithc/0.1/build/build/ithc-dma.c: In function ‘ithc_dma_data_alloc’:
/var/lib/dkms/ithc/0.1/build/build/ithc-dma.c:86:47: error: implicit declaration of function ‘vmap’; did you mean ‘kmap’? [-Werror=implicit-function-declaration]
   86 |                         b->addr = sgt->addr = vmap(pages, prds->num_pages, 0, PAGE_KERNEL);
      |                                               ^~~~
      |                                               kmap
/var/lib/dkms/ithc/0.1/build/build/ithc-dma.c:86:45: warning: assignment to ‘void *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
   86 |                         b->addr = sgt->addr = vmap(pages, prds->num_pages, 0, PAGE_KERNEL);
      |                                             ^
cc1: some warnings being treated as errors
make[3]: *** [scripts/Makefile.build:244: /var/lib/dkms/ithc/0.1/build/build/ithc-dma.o] Error 1
make[3]: *** Waiting for unfinished jobs....
In file included from /var/lib/dkms/ithc/0.1/build/build/ithc-main.c:3:
/var/lib/dkms/ithc/0.1/build/build/ithc-main.c: In function ‘ithc_start’:
/var/lib/dkms/ithc/0.1/build/build/ithc-main.c:335:15: error: implicit declaration of function ‘devm_device_add_groups’; did you mean ‘devm_device_add_group’? [-Werror=implicit-function-declaration]
  335 |         CHECK(devm_device_add_groups, &pci->dev, ithc_attribute_groups);
      |               ^~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/ithc/0.1/build/build/ithc.h:24:35: note: in definition of macro ‘CHECK’
   24 | #define CHECK(fn, ...) ({ int r = fn(__VA_ARGS__); if (r < 0) pci_err(ithc->pci, "%s: %s failed with %i\n", __func__, #fn, r); r; })
      |                                   ^~
cc1: some warnings being treated as errors
make[3]: *** [scripts/Makefile.build:244: /var/lib/dkms/ithc/0.1/build/build/ithc-main.o] Error 1
make[2]: *** [/usr/src/linux-headers-6.10.10-surface-1/Makefile:1940: /var/lib/dkms/ithc/0.1/build/build] Error 2
make[1]: *** [Makefile:240: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-6.10.10-surface-1'
make: *** [Makefile:8: default] Error 2


Not sure the problem is a common issue or only occurred at my system(may be something wrong in my system)?

**Comment by quo** [comment]
@ocean1ee1
You still have an older version ithc installed.
You can remove it using `sudo dkms remove ithc/0.1 --all`, since the current Surface kernel already contains an up-to-date version of ithc.

**Comment by ocean1ee1** [comment]
@quo Thanks for your reply so quickly. It helps a lot

Currently I installed latest surface kernel with no error after run the remove command.

However right now I had to blacklist ipu6 to boot with the latest surface kernel, and I feel the boot process via latest kernel is much slower than via my own complied kernel(only added some modification to support SP 10 Device based on 6.9 kernel ).

And if used my own kernel to boot, the touch feature is not working, Is there any easy way to make touch feature work again in my own kernel and meantime don't affect the official kernel upgrade in future.

**Comment by ocean1ee1** [comment]
@quo Thank you very much.

I tried make install in my kernel without dkms, but got "rejected by service" response.

I give up my idea, just plan to use the official kernel, it's easier for me. Take it easy, just wait more time to boot :)

Anyway thanks for your support, help me a lot using this new model device.

And this issue can be closed, this latest kernel supports SP 10.
