### ISSUE TITLE
DKMS Issue

### ISSUE THREAD

**Issue by Lennaye** [linux-surface/linux-surface#750]
Hey!
Im trying to install 'virtualbox-dkms', and i am getting the error: 
I think this bug is linux-surface related because it worked before installing linux-surface.

<details><summary>`**output of 'sudo apt install virtualbox-dkms':**` output</summary>

```
lenny@Lenny:~$ sudo apt install virtualbox-dkms
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  linux-headers-5.4.0-99 linux-headers-5.4.0-99-generic
  linux-image-5.4.0-99-generic linux-modules-5.4.0-99-generic
  linux-modules-extra-5.4.0-99-generic
Use 'sudo apt autoremove' to remove them.
The following NEW packages will be installed:
  virtualbox-dkms
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/695 kB of archives.
After this operation, 5.700 kB of additional disk space will be used.
Selecting previously unselected package virtualbox-dkms.
(Reading database ... 376712 files and directories currently installed.)
Preparing to unpack .../virtualbox-dkms_6.1.26-dfsg-3~ubuntu1.20.04.2_amd64.deb 
...
Unpacking virtualbox-dkms (6.1.26-dfsg-3~ubuntu1.20.04.2) ...
Setting up virtualbox-dkms (6.1.26-dfsg-3~ubuntu1.20.04.2) ...
Loading new virtualbox-6.1.26 DKMS files...
Building for 5.16.10-surface
Building initial module for 5.16.10-surface
Error! Bad return status for module build on kernel: 5.16.10-surface (x86_64)
Consult /var/lib/dkms/virtualbox/6.1.26/build/make.log for more information.
dpkg: error processing package virtualbox-dkms (--configure):
 installed virtualbox-dkms package post-installation script subprocess returned 
error exit status 10
Errors were encountered while processing:
 virtualbox-dkms
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
</details>

<details><summary>`**output of /var/lib/dkms/virtualbox/6.1.26/build/make.log** output</summary>

```
DKMS make.log for virtualbox-6.1.26 for kernel 5.16.10-surface (x86_64)
Fri 18 Feb 2022 03:02:24 PM CET
make: Entering directory '/usr/src/linux-headers-5.16.10-surface'
  CC [M]  /var/lib/dkms/virtualbox/6.1.26/build/vboxdrv/linux/SUPDrv-linux.o
  CC [M]  /var/lib/dkms/virtualbox/6.1.26/build/vboxdrv/SUPDrv.o
  CC [M]  /var/lib/dkms/virtualbox/6.1.26/build/vboxdrv/SUPDrvGip.o
  CC [M]  /var/lib/dkms/virtualbox/6.1.26/build/vboxdrv/SUPDrvSem.o
In file included from /var/lib/dkms/virtualbox/6.1.26/build/vboxdrv/include/iprt/types.h:34,
                 from /var/lib/dkms/virtualbox/6.1.26/build/vboxdrv/include/VBox/types.h:33,
                 from /var/lib/dkms/virtualbox/6.1.26/build/vboxdrv/linux/../SUPDrvInternal.h:38,
                 from /var/lib/dkms/virtualbox/6.1.26/build/vboxdrv/linux/SUPDrv-linux.c:32:
/var/lib/dkms/virtualbox/6.1.26/build/vboxdrv/include/iprt/stdarg.h:47:12: fatal error: stdarg.h: No such file or directory
   47 | #  include <stdarg.h>
      |            ^~~~~~~~~~
compilation terminated.
make[2]: *** [scripts/Makefile.build:287: /var/lib/dkms/virtualbox/6.1.26/build/vboxdrv/linux/SUPDrv-linux.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /var/lib/dkms/virtualbox/6.1.26/build/vboxdrv/include/iprt/types.h:34,
                 from /var/lib/dkms/virtualbox/6.1.26/build/vboxdrv/include/VBox/types.h:33,
                 from /var/lib/dkms/virtualbox/6.1.26/build/vboxdrv/SUPDrvInternal.h:38,
                 from /var/lib/dkms/virtualbox/6.1.26/build/vboxdrv/SUPDrv.c:33:
/var/lib/dkms/virtualbox/6.1.26/build/vboxdrv/include/iprt/stdarg.h:47:12: fatal error: stdarg.h: No such file or directory
   47 | #  include <stdarg.h>
      |            ^~~~~~~~~~
compilation terminated.
make[2]: *** [scripts/Makefile.build:287: /var/lib/dkms/virtualbox/6.1.26/build/vboxdrv/SUPDrv.o] Error 1
In file included from /var/lib/dkms/virtualbox/6.1.26/build/vboxdrv/include/iprt/types.h:34,
                 from /var/lib/dkms/virtualbox/6.1.26/build/vboxdrv/include/VBox/types.h:33,
                 from /var/lib/dkms/virtualbox/6.1.26/build/vboxdrv/SUPDrvInternal.h:38,
                 from /var/lib/dkms/virtualbox/6.1.26/build/vboxdrv/SUPDrvGip.c:33:
/var/lib/dkms/virtualbox/6.1.26/build/vboxdrv/include/iprt/stdarg.h:47:12: fatal error: stdarg.h: No such file or directory
   47 | #  include <stdarg.h>
      |            ^~~~~~~~~~
compilation terminated.
make[2]: *** [scripts/Makefile.build:287: /var/lib/dkms/virtualbox/6.1.26/build/vboxdrv/SUPDrvGip.o] Error 1
In file included from /var/lib/dkms/virtualbox/6.1.26/build/vboxdrv/include/iprt/types.h:34,
                 from /var/lib/dkms/virtualbox/6.1.26/build/vboxdrv/include/VBox/types.h:33,
                 from /var/lib/dkms/virtualbox/6.1.26/build/vboxdrv/SUPDrvInternal.h:38,
                 from /var/lib/dkms/virtualbox/6.1.26/build/vboxdrv/SUPDrvSem.c:33:
/var/lib/dkms/virtualbox/6.1.26/build/vboxdrv/include/iprt/stdarg.h:47:12: fatal error: stdarg.h: No such file or directory
   47 | #  include <stdarg.h>
      |            ^~~~~~~~~~
compilation terminated.
make[2]: *** [scripts/Makefile.build:287: /var/lib/dkms/virtualbox/6.1.26/build/vboxdrv/SUPDrvSem.o] Error 1
make[1]: *** [scripts/Makefile.build:549: /var/lib/dkms/virtualbox/6.1.26/build/vboxdrv] Error 2
make: *** [Makefile:1852: /var/lib/dkms/virtualbox/6.1.26/build] Error 2
make: Leaving directory '/usr/src/linux-headers-5.16.10-surface'
```
</details>

### Environment

- Hardware model: Surface Pro 2017 
- Kernel version: Linux Lenny 5.16.10-surface #1 SMP PREEMPT Fri Feb 18 01:38:09 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- Distribution: Linux Mint 20.3

<details><summary>`dmesg` output</summary>
```
**see attached file because i was over character limit**
[dmesg.log](https://github.com/linux-surface/linux-surface/files/8097883/dmesg.log)
```
</details>

**Comment by qzed** [comment]
Something like this can happen when the virtualbox version isn't compatible with the kernel version. According to https://www.virtualbox.org/wiki/Changelog you need at least virtualbox 6.1.30.
