### ISSUE TITLE
Update on Ubuntu 24.04 fails

### ISSUE THREAD

**Issue by markotuerk** [linux-surface/linux-surface#1798]
DKMS make.log for v4l2loopback-0.12.7 for kernel 6.15.1-surface-1 (x86_64)
Mo 23. Jun 21:56:16 CEST 2025
Building v4l2-loopback driver...
make -C /lib/modules/6.15.1-surface-1/build M=/var/lib/dkms/v4l2loopback/0.12.7/build modules
make[1]: Verzeichnis „/usr/src/linux-headers-6.15.1-surface-1“ wird betreten
make[2]: Verzeichnis „/var/lib/dkms/v4l2loopback/0.12.7/build“ wird betreten
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
  You are using:           gcc (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
  CC [M]  v4l2loopback.o
v4l2loopback.c: In function ‘buffer_written’:
v4l2loopback.c:1583:9: error: implicit declaration of function ‘del_timer_sync’ [-Werror=implicit-function-declaration]
 1583 |         del_timer_sync(&dev->sustain_timer);
      |         ^~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[4]: *** [/usr/src/linux-headers-6.15.1-surface-1/scripts/Makefile.build:203: v4l2loopback.o] Fehler 1
make[3]: *** [/usr/src/linux-headers-6.15.1-surface-1/Makefile:2010: .] Fehler 2
make[2]: *** [/usr/src/linux-headers-6.15.1-surface-1/Makefile:248: __sub-make] Fehler 2
make[2]: Verzeichnis „/var/lib/dkms/v4l2loopback/0.12.7/build“ wird verlassen
make[1]: *** [Makefile:248: __sub-make] Fehler 2
make[1]: Verzeichnis „/usr/src/linux-headers-6.15.1-surface-1“ wird verlassen
make: *** [Makefile:43: v4l2loopback.ko] Fehler 2

**Comment by markotuerk** [comment]
output from "apt uppgrade"

Building module:
Cleaning build area...
make -j8 KERNELRELEASE=6.15.1-surface-1 KERNEL_DIR=/lib/modules/6.15.1-surface-1
/build all...(bad exit status: 2)
ERROR (dkms apport): kernel package linux-headers-6.15.1-surface-1 is not suppor
ted
Error! Bad return status for module build on kernel: 6.15.1-surface-1 (x86_64)
Consult /var/lib/dkms/v4l2loopback/0.12.7/build/make.log for more information.
dkms autoinstall on 6.15.1-surface-1/x86_64 failed for ithc(10) v4l2loopback(10)
Error! One or more modules failed to install during autoinstall.
Refer to previous errors for more information.
 * dkms: autoinstall for kernel 6.15.1-surface-1                         [fail] 
run-parts: /etc/kernel/postinst.d/dkms exited with return code 11
update-initramfs: Generating /boot/initrd.img-6.15.1-surface-1
Sourcing file `/etc/default/grub'
Generating grub configuration file ...
Found linux image: /boot/vmlinuz-6.15.1-surface-1
Found initrd image: /boot/initrd.img-6.15.1-surface-1
Found linux image: /boot/vmlinuz-6.14.2-surface-1
Found initrd image: /boot/initrd.img-6.14.2-surface-1
Found linux image: /boot/vmlinuz-6.11.0-26-generic
Found initrd image: /boot/initrd.img-6.11.0-26-generic
Found memtest86+ 64bit EFI image: /memtest86+x64.efi
Warning: os-prober will not be executed to detect other bootable partitions.
Systems on them will not be added to the GRUB boot configuration.
Check GRUB_DISABLE_OS_PROBER documentation entry.
Adding boot menu entry for UEFI Firmware Settings ...
done
dpkg: Fehler beim Bearbeiten des Paketes linux-image-6.15.1-surface-1 (--configu
re):
 »installiertes post-installation-Skript des Paketes linux-image-6.15.1-surface-
1«-Unterprozess gab den Fehlerwert 11 zurück
dpkg: Abhängigkeitsprobleme verhindern Konfiguration von linux-image-surface:
 linux-image-surface hängt ab von linux-image-6.15.1-surface-1 (= 6.15.1-surface
-1); aber:
  Paket linux-image-6.15.1-surface-1 ist noch nicht konfiguriert.

dpkg: Fehler beim Bearbeiten des Paketes linux-image-surface (--configure):
 Abhängigkeitsprobleme - verbleibt unkonfiguriert
Es wurde kein Apport-Bericht verfasst, da die Fehlermeldung darauf hindeutet, da
ss dies lediglich ein Folgefehler eines vorherigen Problems ist.
                                                                Fehler traten au
f beim Bearbeiten von:
 linux-image-6.15.1-surface-1
 linux-image-surface
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by TxHxS** [comment]
+1, exact same behavior here - can´t install the surface kernel.... (on Mint 22.1)

**Comment by mykey** [comment]
I have the same issue. 
If I look in the logfile /var/lib/dkms/v4l2loopback/0.12.7/build/make.log it says the compiler of v4l and the kernel differ.

```cat /var/lib/dkms/v4l2loopback/0.12.7/build/make.log 
DKMS make.log for v4l2loopback-0.12.7 for kernel 6.15.1-surface-2 (x86_64)
di  4 nov 2025 16:01:09 CET
Building v4l2-loopback driver...
make -C /lib/modules/6.15.1-surface-2/build M=/var/lib/dkms/v4l2loopback/0.12.7/build modules
make[1]: Map '/usr/src/linux-headers-6.15.1-surface-2' wordt binnengegaan
make[2]: Map '/var/lib/dkms/v4l2loopback/0.12.7/build' wordt binnengegaan
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
  You are using:           gcc (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
  CC [M]  v4l2loopback.o
v4l2loopback.c: In function ‘buffer_written’:
v4l2loopback.c:1583:9: error: implicit declaration of function ‘del_timer_sync’ [-Werror=implicit-function-declaration]
 1583 |         del_timer_sync(&dev->sustain_timer);
      |         ^~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[4]: *** [/usr/src/linux-headers-6.15.1-surface-2/scripts/Makefile.build:203: v4l2loopback.o] Fout 1
make[3]: *** [/usr/src/linux-headers-6.15.1-surface-2/Makefile:2010: .] Fout 2
make[2]: *** [/usr/src/linux-headers-6.15.1-surface-2/Makefile:248: __sub-make] Fout 2
make[2]: Map '/var/lib/dkms/v4l2loopback/0.12.7/build' wordt verlaten
make[1]: *** [Makefile:248: __sub-make] Fout 2
make[1]: Map '/usr/src/linux-headers-6.15.1-surface-2' wordt verlaten
make: *** [Makefile:43: v4l2loopback.ko] Fout 2
```

**Comment by bittles** [comment]
I was having this problem too and have just held the kernel package back.  Finally decided to try to fix it today and got it working if anyone's still having this problem.  It was caused by an outdated package for v4l2loopback-dkms in ubuntu.  Go ahead and remove that.
```
sudo apt remove v4l2loopback-dkms
```
Install (or reinstall) the new kernel and headers.
```
sudo apt install linux-headers-surface linux-image-surface
```
(or reinstall instead of install)
Reboot.  

If you don't care about the cameras you're fine, if you do download a newer version of v4l2loopback (I used 0.15.3):

```
wget https://github.com/v4l2loopback/v4l2loopback/archive/refs/tags/v0.15.3.zip
```
Extract it and go into dir

```
unzip v4l2loopback-0.15.3.zip
cd v4l2loopback-0.15.3
```
Make and install
```
make && sudo make install
sudo depmod -a
```

Load the module and options at boot
```
echo "v4l2loopback" | sudo tee -a /etc/modules-load.d/v4l2loopback.conf
echo "options v4l2loopback video_nr=42 card_label=\"virtualcam\" exclusive_caps=1 max_buffers=4" | sudo tee -a /etc/modprobe.d/v4l2loopback.conf
sudo update-initramfs -c -k $(uname -r)
```
If you've already got your libcamera and a script to start your frontcam for apps like chrome to use them you should be all set, but figured since I typed all this up I'll just consolidate the whole process here for someone who hasn't.

Install camera firmware:
```
cd /tmp
wget -4 http://archive.ubuntu.com/ubuntu/pool/main/l/linux-firmware/linux-firmware_1.187.tar.gz
tar -xvf linux-firmware_1.187.tar.gz
sudo cp /tmp/linux-firmware/intel/irci_irci_ecr-master_20161208_0213_20170112_1500.bin /lib/firmware/intel/ipu3-fw.bin
rm -r /tmp/linux-firmware
rm -r /tmp/linux-firmware_1.187.tar.gz
```

Install components:
```
sudo apt install build-essential meson ninja-build pkg-config libgnutls28-dev openssl python3-pip python3-yaml python3-ply python3-jinja2 qtbase5-dev libqt5core5a libqt5gui5 libqt5widgets5 qttools5-dev-tools libtiff-dev libevent-dev clang libc++-dev libc++abi-dev -y
sudo apt install gstreamer1.0-tools libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev -y
```
Make build and install libcamera:
```
git clone https://git.libcamera.org/libcamera/libcamera.git
cd libcamera
meson build -Dpipelines=uvcvideo,vimc,ipu3 -Dipas=vimc,ipu3 -Dprefix=/usr -Dgstreamer=enabled -Dv4l2=enabled -Dbuildtype=release
ninja -C build
sudo ninja -C build install
```

All done.  Start your front camera with this command if you're trying to use it in an app that doesn't have libcamera built-in:
```
gst-launch-1.0 libcamerasrc camera-name=\\_SB_.PCI0.I2C2.CAMF ! video/x-raw,width=1280,height=720,framerate=30/1,format=NV12 ! videoconvert ! video/x-raw,format=YUY2 ! queue ! videoconvert ! v4l2sink device=/dev/video42
```

**Comment by bittles** [comment]
Note, anytime you upgrade the kernel using the above, you'll have to rebuild v4l2loopback.  If you want to rebuild it automatically, install dkms and add v4l2loopback to it (force needed since we built and loaded v4l2loopback into the kernel in the last comment):

```
sudo apt install dkms
curl -L https://github.com/umlaeute/v4l2loopback/archive/v0.15.3.tar.gz | sudo tar xvz -C /usr/src
sudo dkms add -m v4l2loopback -v 0.15.3
sudo dkms build -m v4l2loopback -v 0.15.3 --force
sudo dkms install -m v4l2loopback -v 0.15.3 --force
```
