### ISSUE TITLE
[SB2] surface control not working with dgpu

### ISSUE THREAD

**Issue by deb75** [linux-surface/linux-surface#369]
[Description of the bug or feature]

### Environment

- Hardware model: Surface Book 2
- Distribution: Debian Buster

I upgraded all surface relates software to their latest package and compiled the latest kernel 5.10.2

When I tried to get the dgpu status I ran into :
```
sudo surface dgpu get
Error: Cannot access device.
       No such file or directory (os error 2).
```

and it appears that the dgpu is on : 
```
lspci
00:1f.4 SMBus: Intel Corporation Sunrise Point-LP SMBus (rev 21)
01:00.0 Ethernet controller: Marvell Technology Group Ltd. 88W8897 [AVASTAR] 802.11ac Wireless
02:00.0 3D controller: NVIDIA Corporation GP107M [GeForce GTX 1050 Mobile] (rev a1)
03:00.0 Non-Volatile memory controller: SK hynix Device 1527
```

and the device is present : 
```
ls /sys/bus/acpi/devices/
ACPI0003:00  device:1d  device:3d  device:5d  INT0800:00  INT3472:00   LNXPOWER:0a  MSHW0153:00
```

In the boot process I noticed : 
```
[    1.383613] surface_hotplug MSHW0153:00: failed to set up IRQ 0: -517
[    1.390189] ACPI Warning: \_SB.SHPS._DSM: Argument #4 type mismatch - Found [Integer], ACPI requires [Package] (20200717/nsarguments-66)
```

This occurs with 5.10.2 kernel. I tried with 5.9.16 ... same issue. But it still works well with my previous 5.9.1 kernel.

For all kernels I use the same custom configuration.

**Comment by qzed** [comment]
> When I tried to get the dgpu status I ran into :
> 
> ```
> sudo surface dgpu get
> Error: Cannot access device.
>        No such file or directory (os error 2).
> ```

This is expected. DGPU power cannot be controlled manually any more and is instead fully handled by the kernel. See https://github.com/linux-surface/surface-hotplug/wiki/Runtime-Power-Management for details. This basically means if you blacklist all dGPU related modules and set `power/control` of the dGPU device to `auto`, it will be powered off automatically by the kernel. If you don't blacklist drivers, the GPU is probably going to be in use in some way (e.g. indirectly through the X11 or Wayland) and will be kept powered on. Note that you can blacklist modules during boot and then un-blacklist and load them when needed (the system76 tool should do something like that, I think).

> In the boot process I noticed :
> 
> ```
> [    1.383613] surface_hotplug MSHW0153:00: failed to set up IRQ 0: -517
> ```

Error 517 is `EPROBE_DEFER`, so that message can be ignored (if it doesn't come up later again).

**Comment by deb75** [comment]
Thanks for the explanations.

Indeed, following the wiki, everything runs fine.

Unfortunately, I tried to compile the nvidia kernel module, from debian buster backports, but it failed with some compilation errors. My surface kernel version is 5.10.3 and gcc version is 8.3.0. The nvidia backport module version is 450. Did anyone succeeded to compile the nvidia kernel module ?

Regards

**Comment by qzed** [comment]
I'm using 455.45 successfully on Arch. 450 may be too old.
